package artifact

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestStoreRoundTripAndStrictSchema(t *testing.T) {
	store := NewStore(t.TempDir())
	store.newID = func() string { return "intent-test" }
	store.clock = func() time.Time { return time.Date(2026, 8, 28, 1, 2, 3, 0, time.UTC) }
	intent := &Intent{
		RunID: "run-test", Provider: "claude", SessionID: "72b5c55e-d964-45cd-b040-cb29d0d7af05",
		RepoPath: "/repo", GitCommonDir: "/repo/.git", WorktreePath: "/worktree",
		Branch: "feat/test", Head: "abc123",
	}
	if err := store.Create(context.Background(), intent); err != nil {
		t.Fatal(err)
	}
	got, err := store.Get(intent.ID)
	if err != nil {
		t.Fatal(err)
	}
	if got.Status != Armed || got.ID != "intent-test" || got.CreatedAt.IsZero() {
		t.Fatalf("round trip = %+v", got)
	}
	if err := store.Update(context.Background(), got.ID, func(i *Intent) error {
		i.Status = Finalized
		i.ArtifactCommit = "deadbeef"
		return nil
	}); err != nil {
		t.Fatal(err)
	}
	updated, err := store.Get(got.ID)
	if err != nil || updated.ArtifactCommit != "deadbeef" {
		t.Fatalf("updated = %+v, %v", updated, err)
	}

	path := store.path(got.ID)
	body, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	body = []byte(strings.Replace(string(body), `"run_id":`, `"unknown": true, "run_id":`, 1))
	if err := os.WriteFile(path, body, 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err := store.Get(got.ID); err == nil || !strings.Contains(err.Error(), "unknown field") {
		t.Fatalf("unknown field should fail strict decoding: %v", err)
	}
}

func TestFindTranscriptUsesExactPreambleNotMtimeOrBody(t *testing.T) {
	root := t.TempDir()
	history := filepath.Join(root, ".specstory", "history")
	if err := os.MkdirAll(history, 0o755); err != nil {
		t.Fatal(err)
	}
	uuid := "72b5c55e-d964-45cd-b040-cb29d0d7af05"
	wanted := filepath.Join(history, "wanted.md")
	writeTranscript(t, wanted, "Claude Code", uuid, "real")
	decoy := filepath.Join(history, "newer.md")
	writeTranscript(t, decoy, "Codex CLI", "01a0438b-5d41-7e60-b11f-ef9f2ab4c7b2", "quoted "+uuid)
	now := time.Now().Add(time.Hour)
	if err := os.Chtimes(decoy, now, now); err != nil {
		t.Fatal(err)
	}

	got, err := FindTranscript(root, "claude", uuid)
	if err != nil {
		t.Fatal(err)
	}
	if got.Path != wanted || got.Provider != "claude" {
		t.Fatalf("resolved = %+v", got)
	}
}

func TestFindTranscriptRejectsDuplicatePreamble(t *testing.T) {
	root := t.TempDir()
	history := filepath.Join(root, ".specstory", "history")
	if err := os.MkdirAll(history, 0o755); err != nil {
		t.Fatal(err)
	}
	uuid := "72b5c55e-d964-45cd-b040-cb29d0d7af05"
	writeTranscript(t, filepath.Join(history, "one.md"), "Claude Code", uuid, "one")
	writeTranscript(t, filepath.Join(history, "two.md"), "Claude Code", uuid, "two")
	if _, err := FindTranscript(root, "claude", uuid); err == nil || !strings.Contains(err.Error(), "multiple") {
		t.Fatalf("duplicate should fail: %v", err)
	}
}

func TestStableSnapshotDetectsWriter(t *testing.T) {
	path := filepath.Join(t.TempDir(), "transcript.md")
	if err := os.WriteFile(path, []byte("first"), 0o600); err != nil {
		t.Fatal(err)
	}
	go func() {
		time.Sleep(10 * time.Millisecond)
		_ = os.WriteFile(path, []byte("second"), 0o600)
	}()
	if _, err := StableSnapshot(context.Background(), path, 30*time.Millisecond); err == nil || !strings.Contains(err.Error(), "changing") {
		t.Fatalf("moving transcript should fail: %v", err)
	}
	if _, err := StableSnapshot(context.Background(), path, time.Millisecond); err != nil {
		t.Fatalf("stable transcript: %v", err)
	}
}

func writeTranscript(t *testing.T, path, provider, sessionID, body string) {
	t.Helper()
	content := "<!-- Generated by SpecStory, Markdown v2.1.0 -->\n\n# now\n\n<!-- " + provider + " Session " + sessionID + " (now) -->\n\n" + body + "\n"
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}

func TestReadTranscriptSessionRequiresStructuredPreamble(t *testing.T) {
	const session = "01a08f36-adab-7183-ad3c-b58a05162903"
	const generated = "<!-- Generated by SpecStory, Markdown v2.1.0 -->\n"
	const title = "\n# now\n\n"
	metadata := func(id string) string { return "<!-- Codex CLI Session " + id + " (now) -->\n" }
	valid := generated + title + metadata(session)
	for _, tc := range []struct {
		name string
		body string
		ok   bool
	}{
		{name: "generated preamble", body: valid + "\nbody\n", ok: true},
		{name: "uppercase UUID normalizes", body: generated + title + metadata(strings.ToUpper(session)), ok: true},
		{name: "CRLF", body: strings.ReplaceAll(valid, "\n", "\r\n"), ok: true},
		{name: "body mentions do not override metadata", body: valid + "\n```\n" + metadata("52a38f41-fcea-4063-8e87-c68737f39bb8") + "```\n", ok: true},
		{name: "large body does not require a full file read", body: valid + "\n" + strings.Repeat("x", 32<<10), ok: true},
		{name: "short hexadecimal token", body: generated + title + metadata("dead")},
		{name: "hyphens are not UUIDs", body: generated + title + metadata("----")},
		{name: "nil UUID", body: generated + title + metadata("00000000-0000-0000-0000-000000000000")},
		{name: "compact UUID is not canonical", body: generated + title + metadata(strings.ReplaceAll(session, "-", ""))},
		{name: "missing generated marker", body: title + metadata(session)},
		{name: "incomplete generated marker", body: "<!-- Generated by SpecStory\n" + title + metadata(session)},
		{name: "missing title", body: generated + metadata(session)},
		{name: "empty title", body: generated + "# \n" + metadata(session)},
		{name: "body before generated marker", body: "body\n" + valid},
		{name: "fenced entire preamble", body: "```markdown\n" + valid + "```\n"},
		{name: "fenced metadata", body: generated + title + "```markdown\n" + metadata(session) + "```\n"},
		{name: "early body metadata mention", body: generated + title + "body\n" + metadata(session)},
		{name: "blockquote metadata", body: generated + title + "> " + metadata(session)},
		{name: "incomplete metadata", body: generated + title + "<!-- Codex CLI Session " + session + " (now)\n"},
		{name: "trailing metadata content", body: generated + title + strings.TrimSuffix(metadata(session), "\n") + " body\n"},
		{name: "metadata beyond line bound", body: generated + title + strings.Repeat("\n", 12) + metadata(session)},
		{name: "metadata beyond byte bound", body: generated + "# " + strings.Repeat("x", 16<<10) + "\n" + metadata(session)},
	} {
		t.Run(tc.name, func(t *testing.T) {
			path := filepath.Join(t.TempDir(), "session.md")
			if err := os.WriteFile(path, []byte(tc.body), 0o600); err != nil {
				t.Fatal(err)
			}
			provider, id, err := ReadTranscriptSession(path)
			if tc.ok {
				if err != nil || provider != "codex" || id != session {
					t.Fatalf("ReadTranscriptSession = %q %q %v", provider, id, err)
				}
			} else if err == nil || provider != "" || id != "" {
				t.Fatalf("unproven preamble returned ownership: %q %q %v", provider, id, err)
			}
		})
	}
}

func TestReadTranscriptSessionRejectsSymlinkAndLateMentions(t *testing.T) {
	history := filepath.Join(t.TempDir(), ".specstory", "history")
	if err := os.MkdirAll(history, 0o755); err != nil {
		t.Fatal(err)
	}
	uuid := "01a08f36-adab-7183-ad3c-b58a05162903"
	transcript := filepath.Join(history, "session.md")
	writeTranscript(t, transcript, "Codex CLI", uuid, "body")
	if provider, session, err := ReadTranscriptSession(transcript); err != nil || provider != "codex" || session != uuid {
		t.Fatalf("ReadTranscriptSession = %q %q %v", provider, session, err)
	}
	link := filepath.Join(history, "link.md")
	if err := os.Symlink(transcript, link); err == nil {
		if _, _, err := ReadTranscriptSession(link); err == nil {
			t.Fatal("symlinked transcript proved a session")
		}
	}
	late := filepath.Join(history, "late.md")
	body := strings.Repeat("line\n", 20) + "<!-- Claude Code Session " + uuid + " (later) -->\n"
	if err := os.WriteFile(late, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	if _, _, err := ReadTranscriptSession(late); err == nil {
		t.Fatal("late session mention proved a session")
	}
}
