package artifact

import (
	"bufio"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/daviddwlee84/dev-cli/internal/pathx"
	"github.com/google/uuid"
)

var transcriptSessionLine = regexp.MustCompile(`^<!-- ([^-][^<]*) Session ([0-9a-fA-F-]+) \(`)
var specStoryGeneratedLine = regexp.MustCompile(`^<!-- Generated by SpecStory, Markdown v[0-9]+\.[0-9]+\.[0-9]+ -->$`)
var specStorySessionLine = regexp.MustCompile(`^<!-- ([A-Za-z][A-Za-z0-9 -]*) Session ([0-9a-fA-F-]+) \([^<>\r\n]+\) -->$`)

type Transcript struct {
	Path      string
	Provider  string
	SessionID string
}

type Snapshot struct {
	Size    int64
	ModTime time.Time
	SHA256  string
}

// FindTranscript selects exactly one SpecStory transcript by its anchored
// preamble session UUID. UUID mentions later in a transcript are never used.
func FindTranscript(worktree, provider, sessionID string) (Transcript, error) {
	history := filepath.Join(worktree, ".specstory", "history")
	entries, err := os.ReadDir(history)
	if err != nil {
		return Transcript{}, err
	}
	var matches []Transcript
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".md") {
			continue
		}
		path := filepath.Join(history, entry.Name())
		inside, err := pathx.Contains(history, path)
		if err != nil || !inside {
			continue
		}
		gotProvider, gotSession, err := transcriptPreamble(path)
		if err != nil || gotSession != sessionID || (provider != "" && gotProvider != provider) {
			continue
		}
		matches = append(matches, Transcript{Path: path, Provider: gotProvider, SessionID: gotSession})
	}
	switch len(matches) {
	case 1:
		return matches[0], nil
	case 0:
		return Transcript{}, fmt.Errorf("no SpecStory transcript with preamble session %s:%s", provider, sessionID)
	default:
		return Transcript{}, fmt.Errorf("multiple SpecStory transcripts have preamble session %s:%s", provider, sessionID)
	}
}

// ReadTranscriptSession proves the bounded SpecStory preamble identity of one
// regular transcript file. Unlike legacy transcript lookup, ownership proof
// requires the generated marker, title, and a complete canonical session UUID
// before any body content. Symlinks and body/fenced UUID mentions never prove it.
func ReadTranscriptSession(path string) (provider, sessionID string, err error) {
	info, err := os.Lstat(path)
	if err != nil {
		return "", "", err
	}
	if !info.Mode().IsRegular() {
		return "", "", fmt.Errorf("SpecStory transcript is not a regular file")
	}
	file, err := os.Open(path)
	if err != nil {
		return "", "", err
	}
	defer file.Close()
	opened, err := file.Stat()
	if err != nil {
		return "", "", err
	}
	if !os.SameFile(info, opened) {
		return "", "", fmt.Errorf("SpecStory transcript changed while opening")
	}
	provider, sessionID, err = specStoryPreamble(file)
	if err != nil {
		return "", "", err
	}
	current, err := os.Lstat(path)
	if err != nil {
		return "", "", err
	}
	if !current.Mode().IsRegular() || !os.SameFile(info, current) || info.Size() != current.Size() || !info.ModTime().Equal(current.ModTime()) {
		return "", "", fmt.Errorf("SpecStory transcript changed while reading")
	}
	return provider, sessionID, nil
}

func specStoryPreamble(reader io.Reader) (provider, sessionID string, err error) {
	scanner := bufio.NewScanner(io.LimitReader(reader, 16<<10))
	heading := false
	for line := 0; line < 12 && scanner.Scan(); line++ {
		text := scanner.Text()
		if line == 0 {
			if !specStoryGeneratedLine.MatchString(text) {
				break
			}
			continue
		}
		if text == "" {
			continue
		}
		if !heading {
			if !strings.HasPrefix(text, "# ") || strings.TrimSpace(strings.TrimPrefix(text, "# ")) == "" {
				break
			}
			heading = true
			continue
		}
		match := specStorySessionLine.FindStringSubmatch(text)
		if len(match) != 3 {
			break // The first nonblank line after the title must be metadata, not body.
		}
		id, parseErr := uuid.Parse(match[2])
		if parseErr != nil || id == uuid.Nil || !strings.EqualFold(id.String(), match[2]) {
			break
		}
		return normalizeProvider(match[1]), id.String(), nil
	}
	if err := scanner.Err(); err != nil {
		return "", "", err
	}
	return "", "", fmt.Errorf("valid SpecStory session preamble not found")
}

func transcriptPreamble(path string) (provider, sessionID string, err error) {
	file, err := os.Open(path)
	if err != nil {
		return "", "", err
	}
	defer file.Close()
	scanner := bufio.NewScanner(io.LimitReader(file, 16<<10))
	for line := 0; scanner.Scan() && line < 12; line++ {
		match := transcriptSessionLine.FindStringSubmatch(scanner.Text())
		if len(match) != 3 {
			continue
		}
		return normalizeProvider(match[1]), match[2], nil
	}
	if err := scanner.Err(); err != nil {
		return "", "", err
	}
	return "", "", fmt.Errorf("SpecStory session preamble not found")
}

func normalizeProvider(label string) string {
	label = strings.ToLower(strings.TrimSpace(label))
	for _, provider := range []string{"claude", "codex", "cursor", "gemini", "antigravity", "deepseek", "droid"} {
		if strings.Contains(label, provider) {
			return provider
		}
	}
	if first, _, ok := strings.Cut(label, " "); ok {
		return first
	}
	return label
}

// StableSnapshot requires the transcript bytes and metadata to remain unchanged
// across a settle interval.
func StableSnapshot(ctx context.Context, path string, settle time.Duration) (Snapshot, error) {
	if settle <= 0 {
		settle = 250 * time.Millisecond
	}
	first, err := snapshot(path)
	if err != nil {
		return Snapshot{}, err
	}
	select {
	case <-ctx.Done():
		return Snapshot{}, ctx.Err()
	case <-time.After(settle):
	}
	second, err := snapshot(path)
	if err != nil {
		return Snapshot{}, err
	}
	if first.Size != second.Size || !first.ModTime.Equal(second.ModTime) || first.SHA256 != second.SHA256 {
		return Snapshot{}, fmt.Errorf("transcript is still changing")
	}
	return second, nil
}

func snapshot(path string) (Snapshot, error) {
	info, err := os.Lstat(path)
	if err != nil {
		return Snapshot{}, err
	}
	if !info.Mode().IsRegular() {
		return Snapshot{}, fmt.Errorf("transcript is not a regular file")
	}
	file, err := os.Open(path)
	if err != nil {
		return Snapshot{}, err
	}
	defer file.Close()
	hash := sha256.New()
	if _, err := io.Copy(hash, file); err != nil {
		return Snapshot{}, err
	}
	return Snapshot{Size: info.Size(), ModTime: info.ModTime(), SHA256: hex.EncodeToString(hash.Sum(nil))}, nil
}
