package cli_test

import (
	"encoding/json"
	"path/filepath"
	"strings"
	"testing"
)

func TestCoCommitCLIRejectsMixedLanesWithoutIndexEffects(t *testing.T) {
	h := newHarness(t)
	h.repo.Write("feature.txt", "reviewed product\n")
	h.repo.Git("add", "feature.txt")
	before := h.repo.Git("diff", "--cached", "--binary")
	head := h.repo.Git("rev-parse", "HEAD")
	for _, args := range [][]string{
		{"prepare", h.repo.Root, "--closeout", "unknown"},
		{"prepare", h.repo.Root, "--no-plan"},
		{"prepare", h.repo.Root, "--message-file", "message.txt"},
		{"prepare", h.repo.Root, "--closeout", "co-commit"},
		{"prepare", h.repo.Root, "--closeout", "co-commit", "--no-plan", "--plan", "one.md"},
		{"prepare", h.repo.Root, "--closeout", "co-commit", "--plan", "one.md", "--plan", "two.md"},
	} {
		if _, _, err := h.run(args...); err == nil {
			t.Fatalf("invalid lane arguments succeeded: %v", args)
		}
		if h.repo.Git("rev-parse", "HEAD") != head || h.repo.Git("diff", "--cached", "--binary") != before {
			t.Fatalf("invalid lane arguments mutated Git: %v", args)
		}
	}
}

func TestArtifactPreparationJSONKeepsDefaultLane(t *testing.T) {
	h := newHarness(t)
	const id = "72b5c55e-d964-45cd-b040-cb29d0d7af05"
	h.repo.Write(".specstory/history/selected.md", "<!-- Generated by SpecStory, Markdown v2.1.0 -->\n# Review\n<!-- Claude Code Session "+id+" (now) -->\nbody\n")
	out := h.mustRun("prepare", h.repo.Root, "--session", "claude:"+id, "--specstory-path", ".specstory/history/selected.md", "--json")
	var preparation struct {
		Kind          string `json:"kind"`
		SchemaVersion int    `json:"schema_version"`
		Intent        struct {
			ID            string `json:"id"`
			Destination   string `json:"destination"`
			SpecStoryPath string `json:"specstory_path"`
		} `json:"intent"`
	}
	if err := json.Unmarshal([]byte(out), &preparation); err != nil {
		t.Fatal(err)
	}
	if preparation.Kind != "artifact_preparation" || preparation.SchemaVersion != 1 || preparation.Intent.ID == "" || preparation.Intent.Destination != "" || !strings.HasSuffix(filepath.ToSlash(preparation.Intent.SpecStoryPath), "/.specstory/history/selected.md") {
		t.Fatalf("default lane JSON changed semantics: %s", out)
	}
	head := h.repo.Git("rev-parse", "HEAD")
	if _, _, err := h.run("artifact", "finalize", "--intent", preparation.Intent.ID, "--allow-commit"); err == nil || !strings.Contains(err.Error(), "co-commit") {
		t.Fatalf("co-commit flags applied to legacy intent: %v", err)
	}
	if h.repo.Git("rev-parse", "HEAD") != head || h.repo.Git("diff", "--cached", "--name-only") != "" {
		t.Fatal("lane refusal staged or committed artifacts")
	}
}

func TestArtifactListJSONHasVersionedEmptyCollection(t *testing.T) {
	h := newHarness(t)
	out := h.mustRun("artifact", "list", "--json")
	var result struct {
		Kind          string            `json:"kind"`
		SchemaVersion int               `json:"schema_version"`
		Handoffs      []json.RawMessage `json:"handoffs"`
	}
	if err := json.Unmarshal([]byte(out), &result); err != nil {
		t.Fatal(err)
	}
	if result.Kind != "artifact_handoffs" || result.SchemaVersion != 1 || result.Handoffs == nil || len(result.Handoffs) != 0 {
		t.Fatalf("invalid empty handoff collection: %s", out)
	}
}
