package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/daviddwlee84/dev-cli/internal/gitx/gittest"
	"github.com/daviddwlee84/dev-cli/internal/runtime"
)

func TestHygieneCLIWriterGuardProtectsArtifactPathAliases(t *testing.T) {
	t.Setenv("HERDR_PANE_ID", "w1:p1")
	t.Setenv("HERDR_WORKSPACE_ID", "w1")
	repo := gittest.New(t)
	backend := &currentPaneRuntime{activityRuntime: &activityRuntime{name: "herdr", activities: []runtime.AgentActivity{{PaneID: "w1:p1", WorkspaceID: "w1", Agent: "codex", Status: "idle", CWD: repo.Root}}}, currentPane: "w1:p1"}
	cli := &hygieneCLI{app: &App{runtimeInstance: backend}}
	// The caller's ordinary checkout edits are allowed by the occupancy service;
	// artifact edits still have to protect the caller's active recorder.
	if err := cli.guard(t.Context(), repo.Root, []string{filepath.Join(repo.Root, "notes.md")}); err != nil {
		t.Fatalf("ordinary caller edit blocked: %v", err)
	}
	for _, name := range []string{".SPECSTORY/history/session.md", ".CoDeX/session.jsonl", ".claude./plans/task.md", ".specstory /history/session.md", "member/.OpenCode/plan.md"} {
		path := filepath.Join(repo.Root, filepath.FromSlash(name))
		if err := cli.guard(t.Context(), repo.Root, []string{path}); err == nil || !strings.Contains(err.Error(), "recognized agent still occupies") {
			t.Errorf("artifact alias bypassed occupancy: %q %v", name, err)
		}
	}
}

const (
	guardCallerSession = "52a38f41-fcea-4063-8e87-c68737f39bb8"
	guardOtherSession  = "01a08f36-adab-7183-ad3c-b58a05162903"
)

func guardFixture(t *testing.T, activities ...runtime.AgentActivity) (*hygieneCLI, string) {
	t.Helper()
	t.Setenv("HERDR_PANE_ID", "w1:p1")
	t.Setenv("HERDR_WORKSPACE_ID", "w1")
	repo := gittest.New(t)
	for index := range activities {
		activities[index].CWD = repo.Root
	}
	backend := &currentPaneRuntime{activityRuntime: &activityRuntime{name: "herdr", activities: activities}, currentPane: "w1:p1"}
	return &hygieneCLI{app: &App{runtimeInstance: backend}}, repo.Root
}

func writeGuardTranscript(t *testing.T, root, name, provider, session string) string {
	t.Helper()
	path := filepath.Join(root, ".specstory", "history", name)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	body := "<!-- Generated by SpecStory, Markdown v2.1.0 -->\n\n# now\n\n<!-- " + provider + " Session " + session + " (now) -->\n\nbody\n"
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}

func TestHygieneCLIWriterGuardExemptsCallerForAnotherSessionTranscript(t *testing.T) {
	cli, root := guardFixture(t, runtime.AgentActivity{PaneID: "w1:p1", WorkspaceID: "w1", Agent: "claude", Status: "working", Session: "claude:" + guardCallerSession})
	other := writeGuardTranscript(t, root, "other.md", "Codex CLI", guardOtherSession)
	if err := cli.guard(t.Context(), root, []string{other}); err != nil {
		t.Fatalf("caller could not repair another session's transcript: %v", err)
	}
}

func TestHygieneCLIWriterGuardRefusesCallersOwnTranscriptEvenWithOverride(t *testing.T) {
	cli, root := guardFixture(t, runtime.AgentActivity{PaneID: "w1:p1", WorkspaceID: "w1", Agent: "claude", Status: "working", Session: "claude:" + guardCallerSession})
	own := writeGuardTranscript(t, root, "own.md", "Claude Code", guardCallerSession)
	cli.app.allowSharedCheckout = true
	if err := cli.guard(t.Context(), root, []string{own}); err == nil || !strings.Contains(err.Error(), "own live transcript") {
		t.Fatalf("caller's own live transcript was editable: %v", err)
	}
}

func TestHygieneCLIWriterGuardUnprovenCallerRequiresAllowSharedCheckout(t *testing.T) {
	cli, root := guardFixture(t, runtime.AgentActivity{PaneID: "w1:p1", WorkspaceID: "w1", Agent: "claude", Status: "idle", Session: "claude:" + guardCallerSession})
	plan := filepath.Join(root, ".claude", "plans", "task.md")
	if err := cli.guard(t.Context(), root, []string{plan}); err == nil || !strings.Contains(err.Error(), "--allow-shared-checkout") {
		t.Fatalf("unproven artifact edit was allowed without override: %v", err)
	}
	cli.app.allowSharedCheckout = true
	if err := cli.guard(t.Context(), root, []string{plan}); err != nil {
		t.Fatalf("explicit shared-checkout override was ignored: %v", err)
	}
}

func TestHygieneCLIWriterGuardOverrideNeverExemptsOtherAgents(t *testing.T) {
	cli, root := guardFixture(t,
		runtime.AgentActivity{PaneID: "w1:p1", WorkspaceID: "w1", Agent: "claude", Status: "idle", Session: "claude:" + guardCallerSession},
		runtime.AgentActivity{PaneID: "w1:p2", WorkspaceID: "w1", Agent: "codex", Status: "idle", Session: "codex:" + guardOtherSession},
	)
	target := writeGuardTranscript(t, root, "third.md", "Codex CLI", "0f0f0f0f-0000-4000-8000-000000000000")
	cli.app.allowSharedCheckout = true
	if err := cli.guard(t.Context(), root, []string{target}); err == nil || !strings.Contains(err.Error(), "stop the writer") {
		t.Fatalf("override exempted another live agent: %v", err)
	}
}
