package cli

import (
	"fmt"
	"strings"

	"github.com/daviddwlee84/dev-cli/internal/config"
	"github.com/daviddwlee84/dev-cli/internal/skill"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

func newSkillCmd(app *App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "skill",
		Short: "Print or install dev's agent skill",
		Long: `dev ships the agent skill that documents it.

Keeping the skill inside the binary is what stops the two drifting: an agent
reading a stale command list is worse than one reading none. The same content
is available as "dev --skill", so a dotfiles installer can sync it without
vendoring a copy.`,
	}
	cmd.AddCommand(newSkillPrintCmd(app), newSkillInstallCmd(app), newSkillSyncCmd(app))
	return cmd
}

func newSkillPrintCmd(app *App) *cobra.Command {
	return &cobra.Command{
		Use:   "print",
		Short: "Print SKILL.md to stdout",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			out, err := skill.Render()
			if err != nil {
				return err
			}
			fmt.Fprint(app.Out, out)
			return nil
		},
	}
}

func newSkillInstallCmd(app *App) *cobra.Command {
	var (
		dir    string
		noLink bool
	)
	cmd := &cobra.Command{
		Use:   "install",
		Short: "Install the skill into the agent skills directory",
		Long: `Write the bundled skill to ~/.agents/skills/dev and symlink it into the
per-tool skill directories that exist on this machine (~/.claude/skills).

Re-running is a no-op when nothing changed, so this is safe to call from a
dotfiles bootstrap on every apply.`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			target := dir
			if target == "" {
				target = skill.DefaultDir()
			}
			res, err := skill.Install(config.Expand(target), !noLink)
			if err != nil {
				return err
			}
			switch {
			case len(res.Written) == 0:
				fmt.Fprintf(app.Out, "skill already current at %s\n", config.Contract(res.Dir))
			default:
				fmt.Fprintf(app.Out, "installed %d file(s) to %s\n", len(res.Written), config.Contract(res.Dir))
				for _, f := range res.Written {
					fmt.Fprintf(app.Out, "   %s\n", f)
				}
			}
			for _, l := range res.Links {
				fmt.Fprintf(app.Out, "   linked %s\n", config.Contract(l))
			}
			return nil
		},
	}
	f := cmd.Flags()
	f.StringVar(&dir, "dir", "", "install directory (default: ~/.agents/skills/dev)")
	f.BoolVar(&noLink, "no-link", false, "do not symlink into per-tool skill directories")
	return cmd
}

func newSkillSyncCmd(app *App) *cobra.Command {
	var check bool
	cmd := &cobra.Command{
		Use:   "sync",
		Short: "Regenerate the skill's command reference from the live command tree",
		Long: `Rewrite the generated section of the skill's command reference from this
binary's actual command tree, so the documented flags can never drift from the
implemented ones.

With --check, report drift and exit non-zero instead of writing — the form to
wire into CI or a pre-push hook.`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			generated := generateCommandReference(cmd.Root())
			return syncCommandReference(app, generated, check)
		},
	}
	cmd.Flags().BoolVar(&check, "check", false, "report drift and exit non-zero instead of writing")
	return cmd
}

// generateCommandReference renders the whole command tree as markdown. This is
// the single source of truth for what the skill tells an agent dev can do.
func generateCommandReference(root *cobra.Command) string {
	var b strings.Builder
	b.WriteString("<!-- generated by `dev skill sync`; do not edit by hand -->\n\n")
	writeCommand(&b, root, 0)
	return b.String()
}

func writeCommand(b *strings.Builder, c *cobra.Command, depth int) {
	if c.Hidden || c.Name() == "no-help" || c.Name() == "completion" {
		return
	}
	if depth > 0 {
		fmt.Fprintf(b, "### `%s`\n\n%s\n\n", c.CommandPath(), firstLine(c.Short))
		if usage := c.UseLine(); usage != "" {
			fmt.Fprintf(b, "```\n%s\n```\n\n", usage)
		}
		if flags := renderFlags(c); flags != "" {
			b.WriteString(flags)
			b.WriteString("\n")
		}
	}
	for _, sub := range c.Commands() {
		writeCommand(b, sub, depth+1)
	}
}

func renderFlags(c *cobra.Command) string {
	var b strings.Builder
	c.LocalNonPersistentFlags().VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		name := "--" + f.Name
		if f.Shorthand != "" {
			name = "-" + f.Shorthand + ", " + name
		}
		fmt.Fprintf(&b, "- `%s` — %s\n", name, f.Usage)
	})
	return b.String()
}

func firstLine(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}
