package hygiene

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/daviddwlee84/dev-cli/internal/safefile"
	"github.com/daviddwlee84/dev-cli/internal/sshhost"
	"go.yaml.in/yaml/v3"
)

const HookConfig = `repos:
  - repo: local
    hooks:
      - id: dev-hygiene
        name: Repository secret and privacy policy
        language: system
        entry: dev hygiene scan --scope staged
        pass_filenames: false
        always_run: true
        require_serial: true
        verbose: true
        stages: [pre-commit]
`

type Status struct {
	SchemaVersion     int               `json:"schema_version"`
	RepoID            string            `json:"repo_id"`
	Tools             map[string]string `json:"tools"`
	Policy            Policy            `json:"policy"`
	Sources           []string          `json:"sources"`
	Hook              string            `json:"hook"`
	HookScope         string            `json:"hook_scope"`
	Configured        bool              `json:"configured"`
	Visibility        string            `json:"visibility"`
	Gaps              []string          `json:"gaps,omitempty"`
	VisibilitySource  string            `json:"visibility_source,omitempty"`
	VisibilityChecked time.Time         `json:"visibility_checked,omitempty"`
}

func (s *Service) hooks(ctx context.Context) (string, string, []byte, error) {
	raw, err := gitBytes(ctx, s.Root, nil, "config", "--path", "--get", "core.hooksPath")
	scope := "local"
	var path string
	if err == nil && strings.TrimSpace(string(raw)) != "" {
		scope = "configured"
		path = strings.TrimSpace(string(raw))
		if !filepath.IsAbs(path) {
			path = filepath.Join(s.Root, path)
		}
		path = filepath.Join(path, "pre-commit")
	} else {
		path = filepath.Join(s.Common, "hooks", "pre-commit")
	}
	var body []byte
	if scope == "local" {
		common, held, e := safefile.OpenRoot(s.Common)
		if e != nil {
			return scope, path, nil, e
		}
		defer common.Close()
		hooks, hookInfo, e := safefile.OpenChildRoot(common, "hooks")
		if errors.Is(e, fs.ErrNotExist) {
			return scope, path, nil, nil
		}
		if e != nil {
			return scope, path, nil, e
		}
		defer hooks.Close()
		body, _, err = safefile.ReadStableRegular(ctx, hooks, "pre-commit", nil, 1<<20)
		if e = safefile.VerifyRoot(s.Common, held); e != nil {
			return scope, path, nil, e
		}
		if e = safefile.VerifyChildRoot(common, "hooks", hookInfo); e != nil {
			return scope, path, nil, e
		}
	} else {
		body, err = safefile.ReadStablePath(ctx, path, 1<<20)
	}
	if errors.Is(err, fs.ErrNotExist) {
		return scope, path, nil, nil
	}
	if err != nil {
		return scope, path, nil, errors.New("effective hook cannot be read safely")
	}
	return scope, path, body, nil
}
func (s *Service) hooksToken(ctx context.Context) (string, error) {
	scope, path, body, err := s.hooks(ctx)
	if err != nil {
		return "", err
	}
	config, e := safefile.ReadStablePath(ctx, filepath.Join(s.Root, ".pre-commit-config.yaml"), 1<<20)
	if e != nil && !errors.Is(e, fs.ErrNotExist) {
		return "", e
	}
	return digest([]byte(scope + path + string(body) + digest(config))), nil
}
func (s *Service) checkHooksToken(ctx context.Context, want string) error {
	got, err := s.hooksToken(ctx)
	if err != nil || got != want {
		return ErrStale
	}
	return nil
}
func (s *Service) Status(ctx context.Context) (Status, error) {
	r := Status{SchemaVersion: 1, RepoID: s.RepoID, Policy: s.Policy, Sources: s.Sources, Tools: map[string]string{}, Visibility: "unknown"}
	for _, name := range []string{"pre-commit", "gitleaks"} {
		if _, err := exec.LookPath(name); err != nil {
			r.Tools[name] = "missing"
			r.Gaps = append(r.Gaps, name+"_missing")
		} else {
			r.Tools[name] = "available"
		}
	}
	scope, path, body, err := s.hooks(ctx)
	r.HookScope = scope
	if err != nil {
		r.Hook = "unverified"
		r.Gaps = append(r.Gaps, "hook_unreadable")
	} else if len(body) == 0 {
		r.Hook = "missing"
	} else {
		info, e := os.Stat(path)
		recognized := bytes.Contains(body, []byte("File generated by pre-commit")) || bytes.Contains(body, []byte("exec pre-commit run --config .pre-commit-config.yaml"))
		if e == nil && (info.Mode()&0o111 != 0 || filepath.VolumeName(path) != "") && recognized {
			r.Hook = "recognized"
		} else {
			r.Hook = "unverified"
		}
	}
	b, err := safefile.ReadStablePath(ctx, filepath.Join(s.Root, ".pre-commit-config.yaml"), 1<<20)
	if err == nil {
		var node yaml.Node
		if yaml.Unmarshal(b, &node) == nil {
			r.Configured = validHygieneHook(&node)
		}
	}
	if !r.Configured {
		r.Gaps = append(r.Gaps, "hygiene_hook_not_configured")
	}
	if _, err = safefile.ReadStablePath(ctx, filepath.Join(s.Root, ".gitleaks.toml"), 1<<20); err != nil {
		r.Gaps = append(r.Gaps, "repository_gitleaks_config_missing")
	}
	if r.Hook != "recognized" {
		r.Gaps = append(r.Gaps, "hook_chain_not_verified")
	}
	return r, nil
}
func hasHook(n *yaml.Node, id string) bool {
	if n.Kind == yaml.MappingNode {
		for i := 0; i+1 < len(n.Content); i += 2 {
			if n.Content[i].Value == "id" && n.Content[i+1].Value == id {
				return true
			}
		}
	}
	for _, c := range n.Content {
		if hasHook(c, id) {
			return true
		}
	}
	return false
}
func mergeHook(existing []byte) ([]byte, error) {
	if len(existing) == 0 {
		return []byte(HookConfig), nil
	}
	var doc, add yaml.Node
	if yaml.Unmarshal(existing, &doc) != nil || len(doc.Content) != 1 || doc.Content[0].Kind != yaml.MappingNode {
		return nil, errors.New("existing pre-commit configuration needs manual review")
	}
	if hasHook(&doc, "dev-hygiene") {
		if !validHygieneHook(&doc) {
			return nil, errors.New("existing dev-hygiene hook differs; review its command and stages")
		}
		return existing, nil
	}
	if yaml.Unmarshal([]byte(HookConfig), &add) != nil {
		panic("invalid embedded hook")
	}
	root := doc.Content[0]
	var repos *yaml.Node
	for i := 0; i+1 < len(root.Content); i += 2 {
		if root.Content[i].Value == "repos" {
			repos = root.Content[i+1]
		}
	}
	if repos == nil {
		root.Content = append(root.Content, add.Content[0].Content...)
	} else if repos.Kind == yaml.SequenceNode {
		repos.Content = append(repos.Content, add.Content[0].Content[1].Content...)
	} else {
		return nil, errors.New("existing pre-commit repos must be a list")
	}
	var b bytes.Buffer
	e := yaml.NewEncoder(&b)
	e.SetIndent(2)
	if err := e.Encode(&doc); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}
func (s *Service) PreviewSetup(ctx context.Context, migrate bool) (Plan, error) {
	status, err := s.Status(ctx)
	if err != nil {
		return Plan{}, err
	}
	for _, v := range status.Tools {
		if v == "missing" {
			return Plan{}, errors.New("install pre-commit and gitleaks first; setup never silently skips a missing dependency")
		}
	}
	p, err := s.newPlan(ctx, "hygiene_setup")
	if err != nil {
		return Plan{}, err
	}
	targets := []struct {
		rel     string
		desired []byte
	}{}
	hooksPath := filepath.Join(s.Root, ".pre-commit-config.yaml")
	old, err := safefile.ReadStablePath(ctx, hooksPath, 1<<20)
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return Plan{}, err
	}
	desired, err := mergeHook(old)
	if err != nil {
		return Plan{}, err
	}
	targets = append(targets, struct {
		rel     string
		desired []byte
	}{".pre-commit-config.yaml", desired})
	gitleaksPath := filepath.Join(s.Root, ".gitleaks.toml")
	current, err := safefile.ReadStablePath(ctx, gitleaksPath, 1<<20)
	if errors.Is(err, fs.ErrNotExist) || migrate {
		targets = append(targets, struct {
			rel     string
			desired []byte
		}{".gitleaks.toml", DefaultGitleaks})
	} else if err != nil {
		return Plan{}, err
	} else if len(current) == 0 {
		return Plan{}, errors.New("empty scanner config needs review")
	}
	policyPath := filepath.Join(s.Root, ".dev-cli", "hygiene.toml")
	if _, err := safefile.ReadStablePath(ctx, policyPath, 1<<20); errors.Is(err, fs.ErrNotExist) {
		data, _ := policyBytes(DefaultPolicy())
		targets = append(targets, struct {
			rel     string
			desired []byte
		}{".dev-cli/hygiene.toml", data})
	} else if err != nil {
		return Plan{}, err
	}
	for _, t := range targets {
		if err = s.addChange(ctx, &p, t.rel, filepath.Join(s.Root, filepath.FromSlash(t.rel)), t.desired, 0); err != nil {
			return Plan{}, err
		}
	}
	if status.HookScope == "local" && status.Hook == "missing" {
		p.Plan.HookAction = "install-local"
	} else if status.Hook == "recognized" {
		p.Plan.HookAction = "keep-existing"
	} else {
		return Plan{}, fmt.Errorf("existing hook chain is %s (%s); keep it and integrate the shown hygiene hook manually", status.Hook, status.HookScope)
	}
	p.HooksToken, err = s.hooksToken(ctx)
	if err != nil {
		return Plan{}, err
	}
	effective := s.Policy
	p.Plan.Policy = &effective
	if err = s.savePlan(ctx, &p); err != nil {
		return Plan{}, err
	}
	return p.Plan, nil
}
func installHook(ctx context.Context, root string) error {
	r, err := (sshhost.ExecRunner{}).Run(ctx, sshhost.RunRequest{Name: "pre-commit", Args: []string{"install", "--config", ".pre-commit-config.yaml"}, Dir: root, Display: "install hygiene Git hook"})
	if err != nil || r.ExitCode != 0 {
		return errors.New("pre-commit hook installation failed; generated files retained")
	}
	return nil
}

func mapping(n *yaml.Node, key string) *yaml.Node {
	if n == nil || n.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(n.Content); i += 2 {
		if n.Content[i].Value == key {
			return n.Content[i+1]
		}
	}
	return nil
}
func validHygieneHook(doc *yaml.Node) bool {
	if doc == nil || len(doc.Content) != 1 {
		return false
	}
	repos := mapping(doc.Content[0], "repos")
	if repos == nil || repos.Kind != yaml.SequenceNode {
		return false
	}
	found := 0
	for _, repo := range repos.Content {
		r := mapping(repo, "repo")
		if r == nil || r.Value != "local" {
			continue
		}
		hooks := mapping(repo, "hooks")
		if hooks == nil || hooks.Kind != yaml.SequenceNode {
			continue
		}
		for _, h := range hooks.Content {
			id := mapping(h, "id")
			if id == nil || id.Value != "dev-hygiene" {
				continue
			}
			found++
			for key, want := range map[string]string{"entry": "dev hygiene scan --scope staged", "language": "system", "pass_filenames": "false", "always_run": "true", "require_serial": "true"} {
				n := mapping(h, key)
				if n == nil || n.Value != want {
					return false
				}
			}
			stages := mapping(h, "stages")
			if stages == nil || stages.Kind != yaml.SequenceNode || len(stages.Content) != 1 || stages.Content[0].Value != "pre-commit" {
				return false
			}
		}
	}
	return found == 1
}

// CheckVisibility is an explicit network action and supplies advice only.
func (s *Service) CheckVisibility(ctx context.Context, status *Status, remote string) {
	status.Visibility = "unknown"
	if remote == "" {
		remote = "origin"
	}
	if !identifier.MatchString(remote) {
		status.Gaps = append(status.Gaps, "invalid_remote_selection")
		return
	}
	raw, err := gitBytes(ctx, s.Root, nil, "config", "--get", "remote."+remote+".url")
	if err != nil {
		status.Gaps = append(status.Gaps, "remote_unavailable")
		return
	}
	pattern := regexp.MustCompile(`^(?:https://github\.com/|git@github\.com:)([A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+?)(?:\.git)?/?$`)
	match := pattern.FindStringSubmatch(strings.TrimSpace(string(raw)))
	if match == nil {
		status.Gaps = append(status.Gaps, "visibility_provider_unsupported")
		return
	}
	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	r, err := (sshhost.ExecRunner{}).Run(ctx, sshhost.RunRequest{Name: "gh", Args: []string{"repo", "view", match[1], "--json", "visibility"}, Env: []string{"GH_HOST=github.com"}, Display: "query repository visibility"})
	if err != nil || r.ExitCode != 0 || r.StdoutTruncated {
		status.Gaps = append(status.Gaps, "visibility_unavailable")
		return
	}
	var response struct{ Visibility string }
	if json.Unmarshal(r.Stdout, &response) != nil {
		status.Gaps = append(status.Gaps, "visibility_invalid")
		return
	}
	switch strings.ToLower(response.Visibility) {
	case "public", "private", "internal":
		status.Visibility = strings.ToLower(response.Visibility)
		status.VisibilitySource = "github:" + remote
		status.VisibilityChecked = time.Now().UTC()
	default:
		status.Gaps = append(status.Gaps, "visibility_invalid")
	}
}
