package fleet

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/BurntSushi/toml"
	"github.com/daviddwlee84/dev-cli/internal/lockx"
)

const (
	// ManagedFragmentHeader is timestamp-free so ownership checks and rewrites are
	// deterministic. A changed header is treated as user-authored content.
	ManagedFragmentHeader        = "# Generated by dev ssh; DO NOT EDIT.\n# dev-fleet-fragment: v1\n"
	managedFragmentPrefix        = "ssh-"
	managedFragmentSuffix        = ".toml"
	maxManagedFragmentSize       = 64 << 10
	managedFragmentDirectoryMode = fs.FileMode(0o700)
	managedFragmentFileMode      = fs.FileMode(0o600)
)

var (
	ErrManagedFragmentConflict = errors.New("managed fleet fragment conflict")
	ErrManagedSecurityBackend  = errors.New("managed fleet fragment requires a secure platform writer")

	managedFragmentBeforeLock func(path string)
)

// ManagedHost is the complete v1 payload of a generated fleet fragment. Using
// a distinct type makes it impossible to silently persist primary-only fields
// such as passwords, explicit connection parameters, or defaults.
type ManagedHost struct {
	Name     string `toml:"name" json:"name"`
	SSHAlias string `toml:"ssh_alias" json:"ssh_alias"`
	RemoteOS string `toml:"remote_os" json:"remote_os"`
}

type managedFragmentDocument struct {
	SchemaVersion int         `toml:"schema_version"`
	Host          ManagedHost `toml:"host"`
}

// ManagedFragmentWriteRequest contains both desired and expected prior bytes so
// an injected secure filesystem backend can revalidate immediately before its
// atomic replacement.
type ManagedFragmentWriteRequest struct {
	Path             string
	Content          []byte
	PreviousContent  []byte
	PreviousIdentity fs.FileInfo
	Existed          bool
}

// ManagedFragmentWriter is the seam used by sshhost's native secure filesystem
// backend. A nil writer uses fleet's platform default.
type ManagedFragmentWriter interface {
	WriteManagedFragment(ManagedFragmentWriteRequest) error
}

// ManagedFragmentWriteFunc adapts a function to ManagedFragmentWriter.
type ManagedFragmentWriteFunc func(ManagedFragmentWriteRequest) error

func (write ManagedFragmentWriteFunc) WriteManagedFragment(request ManagedFragmentWriteRequest) error {
	return write(request)
}

// ManagedFragmentRemoveRequest gives an injected remover the exact bytes whose
// ownership was established before removal.
type ManagedFragmentRemoveRequest struct {
	Path             string
	ExpectedContent  []byte
	ExpectedIdentity fs.FileInfo
}

// ManagedFragmentRemover is the seam used by sshhost's native secure filesystem
// backend. A nil remover uses fleet's platform default.
type ManagedFragmentRemover interface {
	RemoveManagedFragment(ManagedFragmentRemoveRequest) error
}

// ManagedFragmentRemoveFunc adapts a function to ManagedFragmentRemover.
type ManagedFragmentRemoveFunc func(ManagedFragmentRemoveRequest) error

func (remove ManagedFragmentRemoveFunc) RemoveManagedFragment(request ManagedFragmentRemoveRequest) error {
	return remove(request)
}

// ManagedFragmentDir derives the generated overlay directory from the selected
// primary configuration path without touching the primary itself.
func ManagedFragmentDir(primaryPath string) string {
	if primaryPath == "" {
		primaryPath = ConfigFile()
	}
	primaryPath = filepath.Clean(primaryPath)
	if strings.HasSuffix(primaryPath, ".toml") {
		return strings.TrimSuffix(primaryPath, ".toml") + ".d"
	}
	return primaryPath + ".d"
}

// ManagedFragmentPath returns the only v1 path dev may own for an SSH alias.
func ManagedFragmentPath(primaryPath, sshAlias string) (string, error) {
	if err := validateManagedAlias(sshAlias); err != nil {
		return "", err
	}
	return filepath.Join(ManagedFragmentDir(primaryPath), managedFragmentPrefix+sshAlias+managedFragmentSuffix), nil
}

// RenderManagedFragment returns the canonical byte representation accepted by
// ParseManagedFragment and the merged loader.
func RenderManagedFragment(host ManagedHost) ([]byte, error) {
	if err := validateManagedHost(host); err != nil {
		return nil, err
	}
	var encoded bytes.Buffer
	encoded.WriteString(ManagedFragmentHeader)
	document := managedFragmentDocument{SchemaVersion: ConfigSchemaVersion, Host: host}
	if err := toml.NewEncoder(&encoded).Encode(document); err != nil {
		return nil, fmt.Errorf("encode managed fleet fragment: %w", err)
	}
	return encoded.Bytes(), nil
}

// ParseManagedFragment validates canonical v1 bytes and filename ownership. It
// does not inspect filesystem metadata; use ValidateManagedFragment for that.
func ParseManagedFragment(fragmentPath string, content []byte) (ManagedHost, error) {
	alias, err := managedAliasFromFilename(filepath.Base(fragmentPath))
	if err != nil {
		return ManagedHost{}, err
	}
	if !bytes.HasPrefix(content, []byte(ManagedFragmentHeader)) {
		return ManagedHost{}, fmt.Errorf("%s has no v1 managed header: %w", fragmentPath, ErrManagedFragmentConflict)
	}
	var document managedFragmentDocument
	metadata, err := toml.Decode(string(content[len(ManagedFragmentHeader):]), &document)
	if err != nil {
		return ManagedHost{}, fmt.Errorf("read managed fleet fragment %s: %v: %w", fragmentPath, err, ErrManagedFragmentConflict)
	}
	if undecoded := metadata.Undecoded(); len(undecoded) > 0 {
		return ManagedHost{}, fmt.Errorf("read managed fleet fragment %s: unknown field(s): %v: %w", fragmentPath, undecoded, ErrManagedFragmentConflict)
	}
	if !metadata.IsDefined("host") {
		return ManagedHost{}, fmt.Errorf("%s must contain exactly one [host] table: %w", fragmentPath, ErrManagedFragmentConflict)
	}
	if document.SchemaVersion != ConfigSchemaVersion {
		return ManagedHost{}, fmt.Errorf("managed fleet fragment %s schema_version %d: want %d: %w", fragmentPath, document.SchemaVersion, ConfigSchemaVersion, ErrManagedFragmentConflict)
	}
	if err := validateManagedHost(document.Host); err != nil {
		return ManagedHost{}, fmt.Errorf("managed fleet fragment %s: %v: %w", fragmentPath, err, ErrManagedFragmentConflict)
	}
	if document.Host.SSHAlias != alias {
		return ManagedHost{}, fmt.Errorf("managed fleet fragment %s ssh_alias %q does not match filename alias %q: %w", fragmentPath, document.Host.SSHAlias, alias, ErrManagedFragmentConflict)
	}
	canonical, err := RenderManagedFragment(document.Host)
	if err != nil {
		return ManagedHost{}, err
	}
	if !bytes.Equal(content, canonical) {
		return ManagedHost{}, fmt.Errorf("managed fleet fragment %s differs from canonical v1 rendering: %w", fragmentPath, ErrManagedFragmentConflict)
	}
	return document.Host, nil
}

// ValidateManagedFragment validates path ownership, file type, private metadata,
// stable bytes, strict schema, and canonical rendering.
func ValidateManagedFragment(fragmentPath string) (ManagedHost, error) {
	if err := validateManagedDirectory(filepath.Dir(fragmentPath)); err != nil {
		return ManagedHost{}, err
	}
	content, _, err := readStableManagedFile(fragmentPath)
	if err != nil {
		return ManagedHost{}, err
	}
	return ParseManagedFragment(fragmentPath, content)
}

// WriteManagedFragment creates or replaces only the derived owned fragment. It
// is idempotent: canonical identical bytes are left untouched, including mtime.
func WriteManagedFragment(ctx context.Context, primaryPath string, host ManagedHost, writer ManagedFragmentWriter) (string, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	if err := ctx.Err(); err != nil {
		return "", err
	}
	fragmentPath, err := ManagedFragmentPath(primaryPath, host.SSHAlias)
	if err != nil {
		return "", err
	}
	desired, err := RenderManagedFragment(host)
	if err != nil {
		return "", err
	}
	if err := validateManagedWriteMerge(primaryPath, fragmentPath, host); err != nil {
		return fragmentPath, err
	}
	previous, err := inspectExistingManagedFragment(fragmentPath)
	if err != nil {
		return fragmentPath, err
	}

	directory := filepath.Dir(fragmentPath)
	if err := prepareManagedFragmentDirectory(directory); err != nil {
		return fragmentPath, fmt.Errorf("prepare managed fleet directory %s: %w", directory, err)
	}
	directoryIdentity, err := managedDirectoryIdentity(directory)
	if err != nil {
		return fragmentPath, err
	}
	if writer == nil {
		writer = osManagedFragmentWriter{}
	}
	request := ManagedFragmentWriteRequest{
		Path: fragmentPath, Content: bytes.Clone(desired), PreviousContent: bytes.Clone(previous.content),
		PreviousIdentity: previous.info, Existed: previous.exists,
	}
	if managedFragmentBeforeLock != nil {
		managedFragmentBeforeLock(fragmentPath)
	}

	err = lockx.WithDir(ctx, directory, "managed fleet fragment", func() error {
		if err := ctx.Err(); err != nil {
			return err
		}
		if err := revalidateManagedDirectoryIdentity(directory, directoryIdentity); err != nil {
			return err
		}
		if err := validateManagedWriteMerge(primaryPath, fragmentPath, host); err != nil {
			return err
		}
		current, err := inspectExistingManagedFragment(fragmentPath)
		if err != nil {
			return err
		}
		if !managedFragmentSnapshotsEqual(current, previous) {
			if current.exists && bytes.Equal(current.content, desired) {
				return nil
			}
			return fmt.Errorf("managed fleet fragment %s changed while waiting for its lock: %w", fragmentPath, ErrManagedFragmentConflict)
		}
		if current.exists && bytes.Equal(current.content, desired) {
			return nil
		}
		if err := ctx.Err(); err != nil {
			return err
		}
		if err := writer.WriteManagedFragment(request); err != nil {
			return fmt.Errorf("write managed fleet fragment %s: %w", fragmentPath, err)
		}
		if err := revalidateManagedDirectoryIdentity(directory, directoryIdentity); err != nil {
			return err
		}
		written, err := inspectExistingManagedFragment(fragmentPath)
		if err != nil {
			return fmt.Errorf("verify managed fleet fragment %s: %w", fragmentPath, err)
		}
		if !written.exists || !bytes.Equal(written.content, desired) {
			return fmt.Errorf("verify managed fleet fragment %s: writer did not install requested bytes", fragmentPath)
		}
		if _, err := LoadConfig(primaryPath); err != nil {
			validationErr := fmt.Errorf("validate merged fleet config after publishing %s: %w", fragmentPath, err)
			rollbackErr := rollbackManagedFragmentPublication(fragmentPath, previous, written)
			if rollbackErr == nil {
				return fmt.Errorf("%w (publication rolled back)", validationErr)
			}
			return errors.Join(validationErr, fmt.Errorf("rollback managed fleet publication %s: %w", fragmentPath, rollbackErr))
		}
		return nil
	})
	return fragmentPath, err
}

// RemoveManagedFragment removes only a canonical owned fragment for the
// requested alias. Missing fragments are already converged and return nil.
func RemoveManagedFragment(ctx context.Context, primaryPath, sshAlias string, remover ManagedFragmentRemover) (string, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	if err := ctx.Err(); err != nil {
		return "", err
	}
	fragmentPath, err := ManagedFragmentPath(primaryPath, sshAlias)
	if err != nil {
		return "", err
	}
	previous, err := inspectExistingManagedFragment(fragmentPath)
	if err != nil {
		return fragmentPath, err
	}
	if !previous.exists {
		return fragmentPath, nil
	}

	directory := filepath.Dir(fragmentPath)
	directoryIdentity, err := managedDirectoryIdentity(directory)
	if err != nil {
		return fragmentPath, err
	}
	if remover == nil {
		remover = osManagedFragmentRemover{}
	}
	if managedFragmentBeforeLock != nil {
		managedFragmentBeforeLock(fragmentPath)
	}
	err = lockx.WithDir(ctx, directory, "managed fleet fragment", func() error {
		if err := ctx.Err(); err != nil {
			return err
		}
		if err := revalidateManagedDirectoryIdentity(directory, directoryIdentity); err != nil {
			return err
		}
		current, err := inspectExistingManagedFragment(fragmentPath)
		if err != nil {
			return err
		}
		if !current.exists {
			return nil
		}
		if !managedFragmentSnapshotsEqual(current, previous) {
			return fmt.Errorf("managed fleet fragment %s changed while waiting for its lock: %w", fragmentPath, ErrManagedFragmentConflict)
		}
		if err := ctx.Err(); err != nil {
			return err
		}
		if err := remover.RemoveManagedFragment(ManagedFragmentRemoveRequest{
			Path: fragmentPath, ExpectedContent: bytes.Clone(previous.content), ExpectedIdentity: previous.info,
		}); err != nil {
			return fmt.Errorf("remove managed fleet fragment %s: %w", fragmentPath, err)
		}
		if err := revalidateManagedDirectoryIdentity(directory, directoryIdentity); err != nil {
			return err
		}
		if _, err := os.Lstat(fragmentPath); !errors.Is(err, fs.ErrNotExist) {
			if err == nil {
				return fmt.Errorf("remove managed fleet fragment %s: remover left the file in place", fragmentPath)
			}
			return fmt.Errorf("verify removal of managed fleet fragment %s: %w", fragmentPath, err)
		}
		return nil
	})
	return fragmentPath, err
}

func validateManagedWriteMerge(primaryPath, fragmentPath string, managed ManagedHost) error {
	cfg, err := LoadConfig(primaryPath)
	if err != nil {
		return fmt.Errorf("validate fleet before writing %s: %w", fragmentPath, err)
	}
	kept := make([]Host, 0, len(cfg.Hosts)+1)
	for _, host := range cfg.Hosts {
		if host.managed && filepath.Clean(host.origin) == filepath.Clean(fragmentPath) {
			continue
		}
		kept = append(kept, host)
	}
	kept = append(kept, Host{
		Name: managed.Name, SSHAlias: managed.SSHAlias, RemoteOS: managed.RemoteOS,
		origin: fragmentPath, managed: true,
	})
	cfg.Hosts = kept
	cfg.ApplyDefaults()
	if err := cfg.Validate(); err != nil {
		return fmt.Errorf("managed fleet fragment %s would make the merged config invalid: %w", fragmentPath, err)
	}
	return nil
}

func loadManagedFragments(primaryPath string) ([]Host, error) {
	directory := ManagedFragmentDir(primaryPath)
	if err := validateManagedDirectory(directory); err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil, nil
		}
		return nil, err
	}
	entries, err := os.ReadDir(directory)
	if err != nil {
		return nil, fmt.Errorf("read managed fleet directory %s: %w", directory, err)
	}
	hosts := make([]Host, 0, len(entries))
	for _, entry := range entries { // os.ReadDir returns lexical filename order.
		if !strings.HasPrefix(entry.Name(), managedFragmentPrefix) || !strings.HasSuffix(entry.Name(), managedFragmentSuffix) {
			continue
		}
		fragmentPath := filepath.Join(directory, entry.Name())
		managed, err := ValidateManagedFragment(fragmentPath)
		if err != nil {
			return nil, err
		}
		hosts = append(hosts, Host{
			Name: managed.Name, SSHAlias: managed.SSHAlias, RemoteOS: managed.RemoteOS,
			origin: fragmentPath, managed: true,
		})
	}
	return hosts, nil
}

type managedFragmentSnapshot struct {
	content []byte
	info    fs.FileInfo
	exists  bool
}

func inspectExistingManagedFragment(fragmentPath string) (managedFragmentSnapshot, error) {
	if _, err := os.Lstat(fragmentPath); errors.Is(err, fs.ErrNotExist) {
		if directoryInfo, directoryErr := os.Lstat(filepath.Dir(fragmentPath)); directoryErr == nil {
			if err := validateManagedDirectoryInfo(filepath.Dir(fragmentPath), directoryInfo); err != nil {
				return managedFragmentSnapshot{}, err
			}
		} else if !errors.Is(directoryErr, fs.ErrNotExist) {
			return managedFragmentSnapshot{}, fmt.Errorf("inspect managed fleet directory %s: %w", filepath.Dir(fragmentPath), directoryErr)
		}
		return managedFragmentSnapshot{}, nil
	} else if err != nil {
		return managedFragmentSnapshot{}, fmt.Errorf("inspect managed fleet fragment %s: %w", fragmentPath, err)
	}
	if err := validateManagedDirectory(filepath.Dir(fragmentPath)); err != nil {
		return managedFragmentSnapshot{}, err
	}
	content, info, err := readStableManagedFile(fragmentPath)
	if err != nil {
		return managedFragmentSnapshot{}, err
	}
	if _, err := ParseManagedFragment(fragmentPath, content); err != nil {
		return managedFragmentSnapshot{}, fmt.Errorf("refuse to replace or remove %s: %w", fragmentPath, err)
	}
	return managedFragmentSnapshot{content: content, info: info, exists: true}, nil
}

func managedFragmentSnapshotsEqual(left, right managedFragmentSnapshot) bool {
	if left.exists != right.exists {
		return false
	}
	if !left.exists {
		return true
	}
	return left.info != nil && right.info != nil && os.SameFile(left.info, right.info) && bytes.Equal(left.content, right.content)
}

func rollbackManagedFragmentPublication(fragmentPath string, previous, published managedFragmentSnapshot) error {
	current, err := inspectExistingManagedFragment(fragmentPath)
	if err != nil {
		return err
	}
	if !managedFragmentSnapshotsEqual(current, published) {
		return fmt.Errorf("published fragment identity is no longer owned: %w", ErrManagedFragmentConflict)
	}
	if !previous.exists {
		if err := removeManagedFragmentOS(ManagedFragmentRemoveRequest{
			Path: fragmentPath, ExpectedContent: bytes.Clone(published.content), ExpectedIdentity: published.info,
		}); err != nil {
			return err
		}
		if _, err := os.Lstat(fragmentPath); !errors.Is(err, fs.ErrNotExist) {
			if err == nil {
				return fmt.Errorf("created fragment remains after rollback: %w", ErrManagedFragmentConflict)
			}
			return err
		}
		return nil
	}
	if err := writeManagedFragmentOS(ManagedFragmentWriteRequest{
		Path: fragmentPath, Content: bytes.Clone(previous.content), PreviousContent: bytes.Clone(published.content),
		PreviousIdentity: published.info, Existed: true,
	}); err != nil {
		return err
	}
	restored, err := inspectExistingManagedFragment(fragmentPath)
	if err != nil {
		return err
	}
	if !restored.exists || !bytes.Equal(restored.content, previous.content) {
		return fmt.Errorf("previous fragment bytes were not restored: %w", ErrManagedFragmentConflict)
	}
	return nil
}

func validateManagedHost(host ManagedHost) error {
	if strings.TrimSpace(host.Name) == "" || host.Name != strings.TrimSpace(host.Name) {
		return errors.New("host.name is required and must be trimmed")
	}
	if err := validateManagedAlias(host.SSHAlias); err != nil {
		return err
	}
	if host.RemoteOS != RemoteOSPOSIX && host.RemoteOS != RemoteOSWindows {
		return fmt.Errorf("host.remote_os %q: want posix or windows", host.RemoteOS)
	}
	return nil
}

func validateManagedAlias(alias string) error {
	if len(alias) == 0 || len(alias) > 200 {
		return fmt.Errorf("managed ssh_alias %q must contain 1-200 portable characters", alias)
	}
	isAlphaNumeric := func(value byte) bool {
		return value >= 'a' && value <= 'z' || value >= '0' && value <= '9'
	}
	if !isAlphaNumeric(alias[0]) || !isAlphaNumeric(alias[len(alias)-1]) {
		return fmt.Errorf("managed ssh_alias %q must start and end with a lowercase letter or digit", alias)
	}
	for index := 1; index < len(alias)-1; index++ {
		value := alias[index]
		if !isAlphaNumeric(value) && value != '.' && value != '_' && value != '-' {
			return fmt.Errorf("managed ssh_alias %q contains a non-portable character", alias)
		}
	}
	return nil
}

func managedAliasFromFilename(name string) (string, error) {
	if !strings.HasPrefix(name, managedFragmentPrefix) || !strings.HasSuffix(name, managedFragmentSuffix) {
		return "", fmt.Errorf("managed fleet fragment filename %q must match ssh-<alias>.toml: %w", name, ErrManagedFragmentConflict)
	}
	alias := strings.TrimSuffix(strings.TrimPrefix(name, managedFragmentPrefix), managedFragmentSuffix)
	if err := validateManagedAlias(alias); err != nil {
		return "", fmt.Errorf("managed fleet fragment filename %q: %v: %w", name, err, ErrManagedFragmentConflict)
	}
	return alias, nil
}

func validateManagedDirectory(directory string) error {
	info, err := os.Lstat(directory)
	if err != nil {
		return fmt.Errorf("inspect managed fleet directory %s: %w", directory, err)
	}
	return validateManagedDirectoryInfo(directory, info)
}

func validateManagedDirectoryInfo(directory string, info fs.FileInfo) error {
	if info.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("managed fleet directory %s is a symlink: %w", directory, ErrManagedFragmentConflict)
	}
	if !info.IsDir() {
		return fmt.Errorf("managed fleet directory %s is not a directory: %w", directory, ErrManagedFragmentConflict)
	}
	if err := validateManagedPermissions(directory, info, managedFragmentDirectoryMode); err != nil {
		return err
	}
	return nil
}

func readStableManagedFile(fragmentPath string) ([]byte, fs.FileInfo, error) {
	before, err := os.Lstat(fragmentPath)
	if err != nil {
		return nil, nil, fmt.Errorf("inspect managed fleet fragment %s: %w", fragmentPath, err)
	}
	if before.Mode()&os.ModeSymlink != 0 {
		return nil, nil, fmt.Errorf("managed fleet fragment %s is a symlink: %w", fragmentPath, ErrManagedFragmentConflict)
	}
	if !before.Mode().IsRegular() {
		return nil, nil, fmt.Errorf("managed fleet fragment %s is not a regular file: %w", fragmentPath, ErrManagedFragmentConflict)
	}
	if err := validateManagedPermissions(fragmentPath, before, managedFragmentFileMode); err != nil {
		return nil, nil, err
	}
	opened, err := os.Open(fragmentPath)
	if err != nil {
		return nil, nil, fmt.Errorf("open managed fleet fragment %s: %w", fragmentPath, err)
	}
	defer opened.Close()
	openedInfo, err := opened.Stat()
	if err != nil {
		return nil, nil, fmt.Errorf("stat managed fleet fragment %s: %w", fragmentPath, err)
	}
	if !os.SameFile(before, openedInfo) {
		return nil, nil, fmt.Errorf("managed fleet fragment %s changed while opening: %w", fragmentPath, ErrManagedFragmentConflict)
	}
	content, err := io.ReadAll(io.LimitReader(opened, maxManagedFragmentSize+1))
	if err != nil {
		return nil, nil, fmt.Errorf("read managed fleet fragment %s: %w", fragmentPath, err)
	}
	if len(content) > maxManagedFragmentSize {
		return nil, nil, fmt.Errorf("managed fleet fragment %s exceeds %d bytes: %w", fragmentPath, maxManagedFragmentSize, ErrManagedFragmentConflict)
	}
	after, err := os.Lstat(fragmentPath)
	if err != nil || after.Mode()&os.ModeSymlink != 0 || !os.SameFile(openedInfo, after) {
		if err == nil {
			err = ErrManagedFragmentConflict
		}
		return nil, nil, fmt.Errorf("managed fleet fragment %s changed while reading: %w", fragmentPath, err)
	}
	return content, after, nil
}

func managedDirectoryIdentity(directory string) (fs.FileInfo, error) {
	info, err := os.Lstat(directory)
	if err != nil {
		return nil, fmt.Errorf("inspect managed fleet directory %s: %w", directory, err)
	}
	if err := validateManagedDirectoryInfo(directory, info); err != nil {
		return nil, err
	}
	return info, nil
}

func revalidateManagedDirectoryIdentity(directory string, expected fs.FileInfo) error {
	current, err := managedDirectoryIdentity(directory)
	if err != nil {
		return err
	}
	if !os.SameFile(expected, current) {
		return fmt.Errorf("managed fleet directory %s changed during operation: %w", directory, ErrManagedFragmentConflict)
	}
	return nil
}

type osManagedFragmentWriter struct{}

func (osManagedFragmentWriter) WriteManagedFragment(request ManagedFragmentWriteRequest) error {
	return writeManagedFragmentOS(request)
}

type osManagedFragmentRemover struct{}

func (osManagedFragmentRemover) RemoveManagedFragment(request ManagedFragmentRemoveRequest) error {
	return removeManagedFragmentOS(request)
}
