package agenthistory

import (
	"bufio"
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/daviddwlee84/dev-cli/internal/configedit"
	"github.com/daviddwlee84/dev-cli/internal/pathx"
	"github.com/google/uuid"
)

func (s *Service) PolicyFingerprint(ctx context.Context) (string, error) {
	a, e := configedit.InspectToken(ctx, s.policyPath())
	if e != nil {
		return "", e
	}
	b, e := configedit.InspectToken(ctx, s.bindingPath())
	if e != nil {
		return "", e
	}
	capture, e := s.captureFingerprint(ctx)
	if e != nil {
		return "", e
	}
	return hash([]byte(a + "\x00" + b + "\x00" + s.Binding.CaptureDir + "\x00" + capture)), nil
}

// LocateSession keeps legacy ambiguity refusal unless an exact path is selected.
func (s *Service) LocateSession(ctx context.Context, session string, selectedPath ...string) (string, error) {
	if e := s.validateCapture(ctx); e != nil {
		return "", e
	}
	if s.Policy.Source != "specstory" {
		return "", errors.New("prepared sessions require SpecStory; use artifact archive --file for exported plans")
	}
	p, id, e := parseSession(session)
	if e != nil {
		return "", e
	}
	files, e := s.sources(ctx)
	if e != nil {
		return "", e
	}
	if len(selectedPath) > 1 {
		return "", errors.New("select one exact SpecStory path")
	}
	if len(selectedPath) == 1 && selectedPath[0] != "" {
		root := s.Root
		if s.Policy.Capture == "external" {
			root = s.Binding.CaptureDir
		}
		path, err := SelectTranscript(root, selectedPath[0], p, id)
		if err != nil {
			return "", err
		}
		for _, file := range files {
			if s.capturePath(file) == path {
				return path, nil
			}
		}
		return "", errors.New("selected transcript is outside the configured capture scope")
	}
	var paths []string
	for _, file := range files {
		path := s.capturePath(file)
		provider, found, err := prefixIdentity(path)
		if err == nil && provider == p && found == id {
			paths = append(paths, path)
		}
	}
	if len(paths) != 1 {
		return "", errors.New("session does not identify one exact SpecStory transcript")
	}
	return paths[0], nil
}

func (s *Service) CheckSessionPlan(ctx context.Context, id, session string, selectedPath ...string) error {
	p, e := s.load(ctx, id)
	if e != nil {
		return e
	}
	provider, sid, e := parseSession(session)
	if e != nil {
		return e
	}
	if p.View.Kind != "artifact_archive" || p.Root != s.Root || p.Policy.ProjectID != s.Policy.ProjectID || len(p.Snapshots) != 1 || p.Snapshots[0].Provider != provider || p.Snapshots[0].SessionID != sid {
		return errors.New("archive plan does not match the prepared session")
	}
	if len(selectedPath) > 0 && selectedPath[0] != "" {
		path, err := s.LocateSession(ctx, session, selectedPath...)
		if err != nil {
			return err
		}
		if p.Snapshots[0].Path != path || s.capturePath(p.Snapshots[0].Logical) != path {
			return errors.New("archive plan does not match the prepared transcript path")
		}
	}
	return nil
}

// SelectTranscript proves an exact regular Markdown file under root. Only the
// trusted root's ancestors may contain platform aliases (for example /var on
// macOS); no symlink in the selected subtree is accepted, even an internal alias.
func SelectTranscript(root, path, provider, sessionID string) (string, error) {
	root, err := pathx.Canonical(root)
	if err != nil {
		return "", err
	}
	rootInfo, err := os.Stat(root)
	if err != nil || !rootInfo.IsDir() {
		return "", errors.New("transcript root is unavailable")
	}
	for _, component := range strings.Split(filepath.ToSlash(path), "/") {
		if component == ".." {
			return "", errors.New("selected transcript contains path traversal")
		}
	}
	if !filepath.IsAbs(path) {
		path = filepath.Join(root, path)
	}
	path = filepath.Clean(path)
	if !strings.HasSuffix(path, ".md") {
		return "", errors.New("selected transcript must be Markdown")
	}
	for probe := path; ; probe = filepath.Dir(probe) {
		info, e := os.Lstat(probe)
		if e != nil {
			return "", e
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return "", errors.New("selected transcript contains a symlink")
		}
		if os.SameFile(rootInfo, info) {
			break
		}
		if filepath.Dir(probe) == probe {
			return "", errors.New("selected transcript is outside its capture root")
		}
	}
	selected, err := pathx.Canonical(path)
	if err != nil {
		return "", err
	}
	inside, err := pathx.Contains(root, selected)
	if err != nil || !inside || selected == root {
		return "", errors.New("selected transcript is outside its capture root")
	}
	gotProvider, gotID, err := ReadTranscriptSession(selected)
	if err != nil {
		return "", err
	}
	if gotProvider != provider || !strings.EqualFold(gotID, sessionID) {
		return "", errors.New("selected transcript does not match the requested provider/session")
	}
	return selected, nil
}

var specStoryGeneratedLine = regexp.MustCompile(`^<!-- Generated by SpecStory, Markdown v[0-9]+\.[0-9]+\.[0-9]+ -->$`)
var specStorySessionLine = regexp.MustCompile(`^<!-- ([A-Za-z][A-Za-z0-9 -]*) Session ([0-9a-fA-F-]+) \([^<>\r\n]+\) -->$`)

// ReadTranscriptSession proves the bounded SpecStory preamble identity of one
// regular transcript file. Unlike legacy transcript lookup, ownership proof
// requires the generated marker, title, and a complete canonical session UUID
// before any body content. Symlinks and body/fenced UUID mentions never prove it.
func ReadTranscriptSession(path string) (provider, sessionID string, err error) {
	info, err := os.Lstat(path)
	if err != nil {
		return "", "", err
	}
	if !info.Mode().IsRegular() {
		return "", "", fmt.Errorf("SpecStory transcript is not a regular file")
	}
	file, err := os.Open(path)
	if err != nil {
		return "", "", err
	}
	defer file.Close()
	opened, err := file.Stat()
	if err != nil {
		return "", "", err
	}
	if !os.SameFile(info, opened) {
		return "", "", fmt.Errorf("SpecStory transcript changed while opening")
	}
	provider, sessionID, err = specStoryPreamble(file)
	if err != nil {
		return "", "", err
	}
	current, err := os.Lstat(path)
	if err != nil {
		return "", "", err
	}
	if !current.Mode().IsRegular() || !os.SameFile(info, current) || info.Size() != current.Size() || !info.ModTime().Equal(current.ModTime()) {
		return "", "", fmt.Errorf("SpecStory transcript changed while reading")
	}
	return provider, sessionID, nil
}

func specStoryPreamble(reader io.Reader) (provider, sessionID string, err error) {
	scanner := bufio.NewScanner(io.LimitReader(reader, 16<<10))
	heading := false
	for line := 0; line < 12 && scanner.Scan(); line++ {
		text := scanner.Text()
		if line == 0 {
			if !specStoryGeneratedLine.MatchString(text) {
				break
			}
			continue
		}
		if text == "" {
			continue
		}
		if !heading {
			if !strings.HasPrefix(text, "# ") || strings.TrimSpace(strings.TrimPrefix(text, "# ")) == "" {
				break
			}
			heading = true
			continue
		}
		match := specStorySessionLine.FindStringSubmatch(text)
		if len(match) != 3 {
			break // The first nonblank line after the title must be metadata, not body.
		}
		id, parseErr := uuid.Parse(match[2])
		if parseErr != nil || id == uuid.Nil || !strings.EqualFold(id.String(), match[2]) {
			break
		}
		return normalizeTranscriptProvider(match[1]), id.String(), nil
	}
	if err := scanner.Err(); err != nil {
		return "", "", err
	}
	return "", "", fmt.Errorf("valid SpecStory session preamble not found")
}

func normalizeTranscriptProvider(label string) string {
	label = strings.ToLower(strings.TrimSpace(label))
	for _, provider := range []string{"claude", "codex", "cursor", "gemini", "antigravity", "deepseek", "droid"} {
		if strings.Contains(label, provider) {
			return provider
		}
	}
	if first, _, ok := strings.Cut(label, " "); ok {
		return first
	}
	return label
}
