package ignore

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

// Extras are the blocks no language template provides but almost every
// repository wants. They are kept separate from the language sections so a
// later regeneration can replace a language block without losing them.
type Extras struct {
	// OS adds the platform's junk files (.DS_Store, Thumbs.db).
	OS bool
	// Editors adds editor and IDE local state.
	Editors bool
	// Agents adds the directories coding-agent harnesses create.
	Agents bool
	// Env adds the usual local secret files.
	Env bool
}

// DefaultExtras is what `dev gitignore` adds unless told otherwise.
func DefaultExtras() Extras { return Extras{OS: true, Editors: true, Agents: true, Env: true} }

const (
	// Markers delimit the region dev manages, so re-running it updates that
	// region and leaves anything the user added by hand untouched.
	blockBegin = "# >>> dev gitignore >>>"
	blockEnd   = "# <<< dev gitignore <<<"
)

// osSection returns the junk files the host platform scatters through a repo.
func osSection() string {
	switch runtime.GOOS {
	case "darwin":
		return `# macOS
.DS_Store
.AppleDouble
.LSOverride
._*
.Spotlight-V100
.Trashes`
	case "windows":
		return `# Windows
Thumbs.db
Thumbs.db:encryptable
ehthumbs.db
Desktop.ini
$RECYCLE.BIN/`
	default:
		return `# Linux
*~
.fuse_hidden*
.directory
.Trash-*
.nfs*`
	}
}

const editorsSection = `# Editors and IDEs
.idea/
*.iml
.vscode/*
!.vscode/settings.json
!.vscode/extensions.json
!.vscode/launch.json
*.swp
*.swo
.nvimlog
.null-ls_*`

// agentsSection covers the directories coding-agent harnesses create inside a
// repository. The worktree entries matter most: an agent's linked checkout
// left untracked makes every `git status` in the main checkout unreadable.
const agentsSection = `# Coding agent harnesses
.claude/worktrees/
.claude/settings.local.json
.aider*
.cursor/rules/_generated/
.specstory/history/`

const envSection = `# Local environment and secrets — never commit real values
.env
.env.*
!.env.example
!.env.template
*.local
.direnv/`

// Compose renders the managed block from the given sections and extras.
func Compose(sections []Section, extras Extras) string {
	var b strings.Builder
	b.WriteString(blockBegin + "\n")
	b.WriteString("# Generated by `dev gitignore`. Edit outside this block, or re-run to update.\n")

	for _, s := range sections {
		fmt.Fprintf(&b, "\n# --- %s (%s) ---\n%s\n", s.Name, s.Source, s.Body)
	}

	var tail []string
	if extras.OS {
		tail = append(tail, osSection())
	}
	if extras.Editors {
		tail = append(tail, editorsSection)
	}
	if extras.Agents {
		tail = append(tail, agentsSection)
	}
	if extras.Env {
		tail = append(tail, envSection)
	}
	for _, t := range tail {
		b.WriteString("\n" + t + "\n")
	}

	b.WriteString(blockEnd + "\n")
	return b.String()
}

// Merge splices a generated block into an existing .gitignore.
//
// Replacing only the delimited region is what makes this safe to re-run: a
// project accumulates hand-written rules over time, and regenerating must
// never be the thing that loses them.
func Merge(existing, block string) string {
	start := strings.Index(existing, blockBegin)
	end := strings.Index(existing, blockEnd)
	if start >= 0 && end > start {
		tailStart := end + len(blockEnd)
		if tailStart < len(existing) && existing[tailStart] == '\n' {
			tailStart++
		}
		return existing[:start] + block + existing[tailStart:]
	}
	if strings.TrimSpace(existing) == "" {
		return block
	}
	if !strings.HasSuffix(existing, "\n") {
		existing += "\n"
	}
	return existing + "\n" + block
}

// HasManagedBlock reports whether a file already carries dev's markers.
func HasManagedBlock(content string) bool {
	return strings.Contains(content, blockBegin) && strings.Contains(content, blockEnd)
}

// Detect infers which language templates a repository needs from the files it
// contains, so `dev gitignore` can be run with no arguments.
func Detect(dir string) []string {
	markers := map[string][]string{
		"Python":       {"pyproject.toml", "requirements.txt", "setup.py", "uv.lock", "Pipfile"},
		"Node":         {"package.json", "pnpm-lock.yaml", "yarn.lock", "bun.lockb"},
		"Go":           {"go.mod"},
		"Rust":         {"Cargo.toml"},
		"Ruby":         {"Gemfile"},
		"Java":         {"pom.xml"},
		"Gradle":       {"build.gradle", "build.gradle.kts"},
		"Elixir":       {"mix.exs"},
		"Terraform":    {"main.tf", ".terraform.lock.hcl"},
		"Dart":         {"pubspec.yaml"},
		"Swift":        {"Package.swift"},
		"Composer":     {"composer.json"},
		"TeX":          {"main.tex"},
		"VisualStudio": {"*.sln"},
	}
	var found []string
	for name, files := range markers {
		for _, f := range files {
			if strings.ContainsRune(f, '*') {
				if matches, _ := filepath.Glob(filepath.Join(dir, f)); len(matches) > 0 {
					found = append(found, name)
					break
				}
				continue
			}
			if _, err := os.Stat(filepath.Join(dir, f)); err == nil {
				found = append(found, name)
				break
			}
		}
	}
	sort.Strings(found)
	return found
}
